### GENERAL SETTINGS ###

# Site settings
title: Shotcut
description: "Shotcut is a free, open source, cross-platform video editor for Windows, Mac and Linux"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/shotcut_web" #important: start with /
url: "http://videomi.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#19667f" #original color "#00b3fe" #"#F70031" shotcut teal #"#1c7a99" #"#1c7a99"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#091F31" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url: 
  - title: instagram
    url: 
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Adress,
    - City, State, Zip
    - United States
email: dan@dennedy.org
tel: (000) 000-0000


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Dan Dennedy
    position: Lead Developer
    text: Bio or Description Here
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Shotcut is a free, open source, cross-platform video editor for Windows, Mac and Linux. Major features include support for a wide range of formats; no import required meaning native timeline editing; Blackmagic Design support for input and preview monitoring; and resolution support to 4k."

#Short text on homepage describing available tutorials.
tutorials:

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Shotcut was conceived in November, 2004 by Charlie Yates, an MLT co-founder and the original lead developer (see the original website here). The current version of Shotcut is a complete rewrite by Dan Dennedy, another MLT co-founder and its current lead. Dan wanted to create a new editor based on MLT and he chose to reuse the Shotcut name since he liked it so much. The current Shotcut originated from the MLT BuildOnMe project created in January, 2011, which was an example project of how to use MLT in a cross-platform Qt 4 project. Later Dan sought to replace the aging Melted GTK+ client, Rugen, with a cross-platform version and needed an app to test the cross-platform compatibility of new MLT features such as WebVfx and Movit, which led him to fork BuildOnMe and start Shotcut."
    author: Dan Dennedy
    position: Lead Developer - Shotcut & MLT
